force-app/main/default/objects/Log_Settings__c/Log_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Store logging preferences</description>
    <label>Log Settings</label>
</CustomObject>

force-app/main/default/objects/Log_Settings__c/fields/Async_Log_Writer_Implementations__c.field-meta.xml
<CustomField>
    <fullName>Async_Log_Writer_Implementations__c</fullName>
    <description>Comma separated list of classes implementing the LogWriterInterface</description>
    <inlineHelpText>Comma separated list of classes implementing the LogWriterInterface</inlineHelpText>
    <label>Async_Log Writer Implementations</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/LogEventTriggerHandler.cls
//Leverage some trigger handler framework
public with sharing class LogEventTriggerHandler {
    public static void handleLogEvents(List<Log_Event__e> events) {
        Log_Settings__c logSettings = Log_Settings__c.getInstance(UserInfo.getUserId());
        //If asynchronous log writers are there, those are dynamically invoked
        if(logSettings != null && logSettings.Is_Enabled__c && String.isNotBlank(logSettings.Async_Log_Writer_Implementations__c)) {
            List<LogWrapper> logs = new List<LogWrapper>();
            for(Log_Event__e event: events) {
                logs.add(new LogWrapper(event));
            }
            LoggerUtils.invokeLogWriters(logs, logSettings.Async_Log_Writer_Implementations__c);
        }
    }

}